spring.application.name=book_management

# 1. Thông tin k?t n?i
spring.datasource.url=jdbc:mysql://localhost:3306/book_management_db
spring.datasource.username=root
spring.datasource.password=Nguyenthuy92@

# 2. C?u hình JPA/Hibernate
# T? ??ng c?p nh?t c?u trúc b?ng d?a trên Class Java
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? câu l?nh Sql trong console ?? d? debug
spring.jpa.show-sql=true

# ??nh d?ng sql cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
